import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-ai-card',
  standalone: true,
  imports: [CommonModule, MatIconModule],
  template: `
    <div class="ai-card" *ngIf="summary || priority">
      <div class="ai-header">
        <div class="title">
          <mat-icon class="ai-icon">auto_awesome</mat-icon>
          <span>AI Insights</span>
        </div>
        <span class="badge">Generated by AI</span>
      </div>
      
      <div class="ai-body">
        <div class="prop-row" *ngIf="priority">
          <span class="label">Priority:</span>
          <span class="chip" [ngClass]="priority.toLowerCase()">{{ priority }}</span>
        </div>
        
        <div class="summary-box" *ngIf="summary">
          <div class="summary-header">
            <mat-icon class="summary-icon">notes</mat-icon>
            <span>Summary</span>
          </div>
          <p class="summary-text">{{ summary }}</p>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .ai-card {
      background: #ffffff;
      border: 1px solid #e2e8f0;
      border-radius: 12px;
      overflow: hidden;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.04);
      margin-top: 1rem;
    }
    .ai-header {
      background: linear-gradient(135deg, #4f46e5 0%, #4338ca 100%);
      padding: 10px 16px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .title {
      display: flex;
      align-items: center;
      gap: 8px;
      font-weight: 600;
      color: #ffffff;
      font-size: 0.95rem;
    }
    .ai-icon {
      color: #fef08a;
      font-size: 20px;
      width: 20px;
      height: 20px;
    }
    .badge {
      background: rgba(255, 255, 255, 0.2);
      color: #ffffff;
      font-size: 0.7rem;
      font-weight: 600;
      padding: 3px 8px;
      border-radius: 10px;
      letter-spacing: 0.5px;
      text-transform: uppercase;
    }
    .ai-body {
      padding: 16px;
    }
    .prop-row {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 12px;
    }
    .label {
      color: #64748b;
      font-weight: 600;
      font-size: 0.88rem;
    }
    .chip {
      padding: 4px 14px;
      border-radius: 20px;
      font-size: 0.82rem;
      font-weight: 700;
      letter-spacing: 0.3px;
      text-transform: capitalize;
    }
    .chip.critical { background: #fee2e2; color: #dc2626; border: 1px solid #fca5a5; }
    .chip.high { background: #ffedd5; color: #ea580c; border: 1px solid #fdba74; }
    .chip.medium { background: #fef9c3; color: #ca8a04; border: 1px solid #fde047; }
    .chip.low { background: #dcfce7; color: #16a34a; border: 1px solid #86efac; }

    .summary-box {
      margin-top: 8px;
      padding: 12px 14px;
      background: #f8fafc;
      border-radius: 8px;
      border: 1px solid #e2e8f0;
      border-left: 4px solid #6366f1;
    }
    .summary-header {
      display: flex;
      align-items: center;
      gap: 6px;
      color: #475569;
      font-size: 0.8rem;
      font-weight: 700;
      text-transform: uppercase;
      margin-bottom: 6px;
    }
    .summary-icon {
      font-size: 16px;
      width: 16px;
      height: 16px;
      color: #6366f1;
    }
    .summary-text {
      margin: 0;
      color: #334155;
      font-size: 0.92rem;
      line-height: 1.5;
    }
  `]
})
export class AiCardComponent {
  @Input() priority?: string;
  @Input() summary?: string;
}
