import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-ai-card',
  standalone: true,
  imports: [CommonModule, MatIconModule],
  template: `
    <div class="ai-card" *ngIf="summary || category || priority">
      <div class="ai-header">
        <div class="title">
          <mat-icon>auto_awesome</mat-icon>
          <span>AI Analysis</span>
        </div>
        <div class="badge">Generated by AI</div>
      </div>
      
      <div class="ai-body">
        <div class="prop-row" *ngIf="category">
          <span class="label">Category:</span>
          <span class="value chip" [ngClass]="category.toLowerCase()">{{ category }}</span>
        </div>
        <div class="prop-row" *ngIf="priority">
          <span class="label">Priority:</span>
          <span class="value chip" [ngClass]="priority.toLowerCase()">{{ priority }}</span>
        </div>
        <div class="prop-row" *ngIf="confidence">
          <span class="label">Confidence:</span>
          <span class="value">{{ confidence }}</span>
        </div>
        
        <div class="summary-box" *ngIf="summary">
          <mat-icon class="quote-icon">format_quote</mat-icon>
          <p>{{ summary }}</p>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .ai-card {
      background: linear-gradient(135deg, rgba(238, 242, 255, 0.5) 0%, rgba(224, 231, 255, 0.5) 100%);
      border: 1px solid #c7d2fe;
      border-radius: 12px;
      overflow: hidden;
      margin-top: 1rem;
    }
    .ai-header {
      background: rgba(224, 231, 255, 0.8);
      padding: 12px 16px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 1px solid #c7d2fe;
    }
    .title {
      display: flex;
      align-items: center;
      gap: 8px;
      font-weight: 600;
      color: #4338ca;
    }
    .title mat-icon {
      color: #6366f1;
    }
    .badge {
      background: #818cf8;
      color: white;
      font-size: 0.75rem;
      font-weight: 600;
      padding: 4px 8px;
      border-radius: 12px;
      text-transform: uppercase;
    }
    .ai-body {
      padding: 16px;
    }
    .prop-row {
      display: flex;
      align-items: center;
      margin-bottom: 12px;
    }
    .label {
      width: 100px;
      color: #64748b;
      font-weight: 500;
      font-size: 0.9rem;
    }
    .chip {
      padding: 4px 12px;
      border-radius: 16px;
      font-size: 0.85rem;
      font-weight: 600;
    }
    /* Dynamic Priority Colors */
    .chip.high { background: rgba(239, 68, 68, 0.1); color: #ef4444; }
    .chip.medium { background: rgba(249, 115, 22, 0.1); color: #f97316; }
    .chip.low { background: rgba(34, 197, 94, 0.1); color: #22c55e; }
    /* Default chip */
    .chip { background: white; border: 1px solid #e2e8f0; color: #475569; }

    .summary-box {
      margin-top: 16px;
      padding: 16px;
      background: white;
      border-radius: 8px;
      border-left: 4px solid #6366f1;
      position: relative;
    }
    .quote-icon {
      position: absolute;
      top: -10px;
      left: 10px;
      color: #c7d2fe;
      background: white;
      padding: 0 4px;
      font-size: 20px;
      height: 20px;
      width: 20px;
    }
    .summary-box p {
      margin: 0;
      color: #334155;
      line-height: 1.5;
      font-style: italic;
    }
  `]
})
export class AiCardComponent {
  @Input() category?: string;
  @Input() priority?: string;
  @Input() confidence?: string;
  @Input() summary?: string;
}
